[build-system]
requires = ["setuptools==80.3.1"]
build-backend = "setuptools.build_meta"

[project]
name = "trans_synergy"
version = "0.0.1"
description = "Implementation of Trans Synergy"
authors = [
  { name = "Nadir Bašić", email = "basicnadir@gmail.com" },
  { name = "Hriskikesh Yadav", email = "hriskikesh.yadav332@gmail.com" },
  { name = "Catarina Freire", email = "catarinaxfreire@gmail.com" },
  { name = "Rajan Puri", email = "rjnunofficial001@gmail.com" },
  { name = "Nina Zukowska", email = "zukowskanina1@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "pandas==2.0.3",
  "numpy==1.24.4",
  "tqdm==4.67.1",
  "zenodo-get==1.6.1",
  "wandb==0.19.10",
  "shap==0.44.1" ,
  "rdkit==2024.3.5",
  "pubchempy==1.0.4",
  "matplotlib==3.10.0",
  "seaborn==0.13.2",
  "fire==0.7.0",
  "h2o==3.46.0.7",
  "scikit-learn==1.6.1"
  "torch",
  # "pyNBS==1.1.0",  # Not on PyPI! Only used for preprocessing.
]

[project.optional-dependencies]
dev = [
  "jupyter",
  "isort==5.13.2",
  "ruff==0.11.8",
  "flake8==7.1.2"
]

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["trans_synergy"]  # package names should match these glob patterns (["*"] by default)
exclude = []  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)