name: transynergy-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  
  - numpy==1.23.5 
  - rdkit
  - pandas
  - scipy
  - scikit-learn
  - scikit-image
  - matplotlib
  - shap
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - tensorflow==2.13
      - torch==2.0.1+cu118
      - wandb
